### ISSUE TITLE
Atom 1.9 compatibility

### ISSUE THREAD

**Issue by sbaack** [braver/typewriter#14] opened 2016-08-01 18:09 UTC
First, thank you for this great package!

I just updated to Atom 1.9 and now I can always scroll the text in the editor horizontally when typewriter is enabled. In addition, Minimap now covers the text. Maybe some of the changes to the display layers mentioned [here](http://blog.atom.io/2016/08/01/atom-1-9-and-1-10-beta.html) are causing this?

**Comment by braver** [comment] 2016-08-01 18:30
Could very well be. I haven't actually used Atom in a while, but I'll have a look at it soon.

**Comment by sbaack** [comment] 2016-08-03 14:04
I found that everything is back to normal when _Soft Wrap At Preferred Line Length_ is deactivated. I'm very sure it was active before I updated to Atom 1.9 and it didn't cause issues then.

**Comment by braver** [comment] 2016-08-09 08:39
I'm not able to reproduce this, but I'm sure there are certain combinations of soft wrap settings that will have this result.

**Comment by braver** [comment] 2016-08-09 08:44
Looking at this some more, I think we might unset `Soft Wrap At Preferred Line Length` for the selected scopes. That should be more reliable, even though it doesn't seem to matter "on my machine". Can you reliably reproduce the layout error you experienced by switching this option on?

**Comment by sbaack** [comment] 2016-08-09 14:15
Funny, I cannot reproduce this anymore. Switching `Soft Wrap At Preferred Line Length` on and off doesn't change anything anymore. Not sure if it was fixed with one of the recent patches to Atom 1.9, I didn't change other settings or installed new packages.

**Comment by braver** [comment] 2016-08-09 14:22
Right, let's close it then.

**Closed as completed** 2016-08-09 14:22 UTC
