### ISSUE TITLE
Minimap gets in the way

### ISSUE THREAD

**Issue by inancgumus** [braver/typewriter#16] opened 2016-08-08 14:46 UTC
I think that width of the addon might be changed according to user needs. 

After 80th character, it wraps or overflows in the pane.

If there is minimap, it gets in the way and sequeze the space more. See the screenshots below.

<img width="799" alt="screen shot 2016-08-08 at 17 46 00" src="https://cloud.githubusercontent.com/assets/621232/17483753/010d533c-5d90-11e6-9f78-413111065527.png">
<img width="804" alt="screen shot 2016-08-08 at 17 45 31" src="https://cloud.githubusercontent.com/assets/621232/17483754/010db372-5d90-11e6-957b-ee231ca56093.png">

**Comment by braver** [comment] 2016-08-09 06:26
Yes, scroll bars also eat space from the 80 columns. I haven't found a solution for this yet.

**Comment by braver** [comment] 2016-08-09 08:47
This is basically a duplicate of #6

**Closed as completed by braver** 2016-08-09 08:47 UTC

**Comment by inancgumus** [comment] 2016-08-09 09:48
Yeah, it looks like so, thanks.
